
package com.chinaunicom.SCService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SCService", targetNamespace = "http://SCService.chinaunicom.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ISCService {

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "invokeReturn", partName = "invokeReturn")
    String invoke(
            @WebParam(name = "xmlData", partName = "xmlData")
                    String xmlData);

}
