/*  =========================================================================
    perf_counter_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef PERF_COUNTER_CLASSES_H_INCLUDED
#define PERF_COUNTER_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/perf_counter.h"

//  Extra headers

//  Opaque class structures to allow forward references
#ifndef PERF_COUNTER_IT_T_DEFINED
typedef struct _perf_counter_it_t perf_counter_it_t;
#define PERF_COUNTER_IT_T_DEFINED
#endif

//  Internal API

#include "perf_counter_it.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef PERF_COUNTER_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
PERF_COUNTER_PRIVATE void
    perf_counter_it_test (bool verbose);

//  Self test for private classes
PERF_COUNTER_PRIVATE void
    perf_counter_private_selftest (bool verbose, const char *subtest);

#endif // PERF_COUNTER_BUILD_DRAFT_API

#endif
