/*  =========================================================================
    perf-counter - generated layer of public API

    Copyright (c) the Authors

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef PERF_COUNTER_LIBRARY_H_INCLUDED
#define PERF_COUNTER_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  PERF_COUNTER version macros for compile-time API detection
#define PERF_COUNTER_VERSION_MAJOR 1
#define PERF_COUNTER_VERSION_MINOR 1
#define PERF_COUNTER_VERSION_PATCH 0

#define PERF_COUNTER_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define PERF_COUNTER_VERSION \
    PERF_COUNTER_MAKE_VERSION(PERF_COUNTER_VERSION_MAJOR, PERF_COUNTER_VERSION_MINOR, PERF_COUNTER_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined PERF_COUNTER_STATIC
#       define PERF_COUNTER_EXPORT
#   elif defined PERF_COUNTER_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define PERF_COUNTER_EXPORT __declspec(dllexport)
#       else
#           define PERF_COUNTER_EXPORT
#       endif
#   elif defined PERF_COUNTER_EXPORTS
#       define PERF_COUNTER_EXPORT __declspec(dllexport)
#   else
#       define PERF_COUNTER_EXPORT __declspec(dllimport)
#   endif
#   define PERF_COUNTER_PRIVATE
#elif defined (__CYGWIN__)
#   define PERF_COUNTER_EXPORT
#   define PERF_COUNTER_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define PERF_COUNTER_PRIVATE __attribute__ ((visibility ("hidden")))
#       define PERF_COUNTER_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define PERF_COUNTER_PRIVATE
#       define PERF_COUNTER_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  PERF_COUNTER_BUILD_DRAFT_API
#define PERF_COUNTER_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases


//  Public classes, each with its own header file

#ifdef PERF_COUNTER_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
PERF_COUNTER_EXPORT void
    perf_counter_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // PERF_COUNTER_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
