version: '2' 

services:
  prod-registry:
    restart: always
    image: registry:2
    container_name: prod-registry
    ports:
      - 5000:5000
    environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: ./auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./prod-registry:/var/lib/registry
      - ./auth:/auth
      #- /path/certs:/certs
      #- /path/auth:/auth
  dev-registry:
    restart: always
    image: registry:2
    container_name: dev-registry
    ports:
      - 5001:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: ./auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./dev-registry:/var/lib/registry
      - ./auth:/auth


