cmake -G "NMake Makefiles" ^
 -DCMAKE_C_FLAGS_DEBUG="/MD" ^
 -DCMAKE_C_FLAGS_RELEASE="/MD /O2 /DNDEBUG" ^
 -DCMAKE_EXE_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_MODULE_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_STATIC_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_INCLUDE_PATH="C:\WINDDK\3790.1830\inc\crt;C:\WINDDK\3790~1.183\inc\ddk\wnet" ^
 -DCMAKE_LIBRARY_PATH="C:\WINDDK\3790~1.183\lib\crt\amd64;C:\WINDDK\3790.1830\lib\wnet\amd64" ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_INSTALL_PREFIX=C:\usr ^
 ..

