/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.hello;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        final App app = new App();
        System.getProperties().store(System.out, app.getGreeting());
    }
}
